### ISSUE TITLE
Incorrect rendering, some details missing

### ISSUE THREAD

**Issue by AlexanderMatveev** [mineatar-io/skin-render#1]
### Source image:

![2845](https://user-images.githubusercontent.com/1456669/235323437-24fe4d7a-0d33-4f30-a77a-81a38691eff6.png)

### Result:

![2845](https://user-images.githubusercontent.com/1456669/235322558-1c1a7c61-a493-4081-b487-24f96be0664d.png)

### Render by other tools I tried:

<img width="501" alt="Снимок экрана 2023-04-29 в 23 42 18" src="https://user-images.githubusercontent.com/1456669/235323416-0b05a3b8-e739-407c-88e7-28bdabafc5a1.png">

**Comment by PassTheMayo** [comment]
Thank you for bringing this issue to my attention. I'm currently in the middle of rewriting this library to support multi-threading, and I will fix this along with that release.

**Comment by PassTheMayo** [comment]
I forgot to reply to this when the issue was fixed, but I pushed a commit 3 days ago that fixed this issue. It's also live on [mineatar.io](https://mineatar.io) as well.

**Comment by DigitalDetective47** [comment]
the top of the right arm shirt still does not render. See my skin (DDetective47)

**Comment by PassTheMayo** [comment]
This issue seems to have gotten fixed sometime between when this issue was created and now, but I am not sure when.
