### ISSUE TITLE
Top side of head is improperly flipped

### ISSUE THREAD

**Issue by t-mart** [mineatar-io/skin-render#2]
The top side of heads is left-right flipped in rendered images. (Additionally, if you have generalized the mapping to all body parts, I would image the other top sides to have the same issue.)

I was not able to get this application to run on my machine, for what it's worth. My results come from the deployed version on <https://mineatar.io> as of today, 2023-10-03. (I could not find the entrypoint for the application. And no executable seemed to be built with `go build`)

Here's a skin image that gradates on the left-right axis from black to white. Rendered in your software, you see will that the top of the head has been flipped improperly.
![lr_gradient](https://github.com/mineatar-io/skin-render/assets/200012/cd0d0b42-83e5-47ba-b53c-4142204c8f88)

Expected result (on another renderer):
![image](https://github.com/mineatar-io/skin-render/assets/200012/5113180e-6e0a-4d0c-881e-ad52220ab7ea)

Because of the 24-hour caching on the site and because I was not able to build the software, I am not able to produce a rendered image. But, hopefully, you can take a look.

**Comment by PassTheMayo** [comment]
Hello, thank you for your report. I have actually received the same report from another person a while ago, but have since forgotten to investigate this issue. I currently plan on looking into this within the next 24 hours and a fix will be implemented shortly proceeding.

As far as attempting to build this on your own, all source code resides in the `src` folder which means that the start command has to refer to these files, using something like `go run src/*.go` or similar, or use the `make run` command which will do the same. If you are still wanting to run this software for yourself, let me know if this fixes that issue.

**Comment by t-mart** [comment]
Are you sure that you are talking about this project? There is no [src/](https://github.com/mineatar-io/skin-render/tree/main/src) directory and the [Makefile](https://github.com/mineatar-io/skin-render/blob/main/Makefile) does not contain a `run` target.

**Comment by PassTheMayo** [comment]
I'm sorry, I did not realize this was the `skin-render` repository. This is actually just a library with exported methods to generate the skins. If you would like to run a copy of the API, that is going to be in the `api-server` repository, and instructions to start that server is in my last message.

If you would like to generate the images directly using this library, you will need to code an interfacing program to do that. The methods are very simple and just take an input image. I'm going to consider making this library into a CLI as well.

**Comment by t-mart** [comment]
It's all good, man. Foremost, this is your project! You're in charge. Just trying to help you out.

For what it's worth, I wrote a similar project in Python, and the mapping was hard to get right. Some faces require reading the image's pixel color data in reverse order.

**Comment by PassTheMayo** [comment]
That's interesting, I've had to do some rotating and reflections but never reading in reverse order. I'll have plenty of time tonight to fix this issue. Additionally, thank you for the gradient test skin. I haven't found anything before that I could use that would help like this.

**Comment by t-mart** [comment]
Sure thing. Here are the two other skins that gradate in the other two axes:

Front to back gradient:
![fb_gradient](https://github.com/mineatar-io/skin-render/assets/200012/d1c79cac-92ab-4519-b933-682f6447995b)

Top to bottom gradient:
![tb_gradient](https://github.com/mineatar-io/skin-render/assets/200012/fca3ac4b-3532-4178-84da-7d8c768b4a6c)

**Comment by t-mart** [comment]
> I've had to do some rotating and reflections but never reading in reverse order

We're talking about the same thing, just two different ways to achieve the same result. For example, if you rotate the x-y plane 180 degrees and then reflect about the x axis, that's the same thing as reading the data in reverse order on the x axis. (It's admittedly hard to reason about this stuff, I'm getting caught up even writing this. I would just keep doing what you're doing, but just apply a reflection about the right axis for this face)

**Comment by PassTheMayo** [comment]
Greatly appreciate all of your help. I'll close this issue whenever I've pushed these changes here in a few hours.

**Comment by PassTheMayo** [comment]
I have published v1.1.0 which resolves this issue, and the live API server should also reflect these changes as well. Please let me know if there is any other problems you may find with my library.
